services:
  - type: web
    name: contact-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx json-server --watch backend/db.json --host 0.0.0.0 --port $PORT

    startCommand: npx json-server --watch backend/db.json --host 0.0.0.0 --port 10000
